;Exercise 1.15.  The sine of an angle (specified in radians) can be computed by making use of the approximation sin x = x if x is sufficiently small, and the trigonometric identity
;sin x = 3sin(x/3) - 4sin^3(x/3)
;to reduce the size of the argument of sin. (For purposes of this exercise an angle is considered ``sufficiently small'' if its magnitude is not greater than 0.1 radians.) These ideas are incorporated in the following procedures:

(define (cube x) (* x x x))
(define (p x) (- (* 3 x) (* 4 (cube x))))
(define (sine angle)
   (if (not (> (abs angle) 0.1))
       angle
       (p (sine (/ angle 3.0)))))

;a.  How many times is the procedure p applied when (sine 12.15) is evaluated?

"p gets applied once for every time you need to divide 12.15 by 3 until it's smaller than 0.1.
That's 5 times."

;b.  What is the order of growth in space and number of steps (as a function of a) used by the process generated by the sine procedure when (sine a) is evaluated?

"The order of growth in space is the depth of the call stack, which, like above, is the number of times
you can divide a by 3 before it is less than 0.1, which is roughly log_3 a. So the order of growth is Theta(log a).

Similarly, the order of growth in time is proportional to the depth of the call stack, and is thus Theta(log a)"