(define (make-point x y)
        (cons x y))
(define (x-point point)
        (car point))
(define (y-point point)
        (cdr point))

(define (print-point point)
        (newline)
        (display "(")
        (display (x-point point))
        (display ",")
        (display (y-point point))
        (display ")"))

;(print-point (make-point 2 7))

(define (make-segment p1 p2)
        (cons p1 p2))
(define (start-segment segment)
        (car segment))
(define (end-segment segment)
        (cdr segment))

(define (mean x y)
        (/ (+ x y) 2))
(define (midpoint-segment segment)
        (make-segment (mean (x-point (start-segment segment))
                            (x-point (end-segment segment)))
                      (mean (y-point (start-segment segment))
                            (y-point (end-segment segment)))))
(print-point(midpoint-segment (make-segment (make-point 2 8) (make-point 1 (- 3)))))