(define (make-account balance password)
        (define (withdraw amount)
                (if (>= balance amount)
                    (begin (set! balance (- balance amount))
                           balance)
                    "Insufficient funds"))
        (define (deposit amount)
                (set! balance (+ balance amount))
                balance)
        (define (dispatch pswd m)
                (cond ((not (eq? pswd password)) (error "Incorrect password"))
                      ((eq? m 'withdraw) withdraw)
                      ((eq? m 'deposit) deposit)
                      (else (error "Unknown request -- MAKE-ACCOUNT" m))))
        dispatch)

(define acc (make-account 100 'secret-password))

((acc 'secret-password 'withdraw) 40)
;60

((acc 'some-other-password 'deposit) 50)
;"Incorrect password"

(define (call-the-cops)
        ("cops called!"))

(define (make-account balance password)
        (define incorrect-password-count 0)
        (define (withdraw amount)
                (if (>= balance amount)
                    (begin (set! balance (- balance amount))
                           balance)
                    "Insufficient funds"))
        (define (deposit amount)
                (set! balance (+ balance amount))
                balance)
        (define (dispatch pswd m)
                (cond ((not (eq? pswd password)) (begin (set! incorrect-password-count (+ incorrect-password-count 1))
                                                        (if (> incorrect-password-count 7)
                                                            call-the-cops)
                                                        (error "Incorrect password")))
                      (else (set! incorrect-password-count 0)))
                (cond ((eq? m 'withdraw) withdraw)
                      ((eq? m 'deposit) deposit)
                      (else (error "Unknown request -- MAKE-ACCOUNT" m))))
        dispatch)

(define safe-acc (make-account 100 'super-secret))

((safe-acc 'some-other-password 'deposit) 50)
((safe-acc 'some-other-password 'deposit) 50)
((safe-acc 'some-other-password 'deposit) 50)
((safe-acc 'some-other-password 'deposit) 50)
((safe-acc 'some-other-password 'deposit) 50)
((safe-acc 'some-other-password 'deposit) 50)
((safe-acc 'some-other-password 'deposit) 50)
((safe-acc 'some-other-password 'deposit) 50)